[FFM-9598] -  jsonVariation always returns default value (#71)
What
Fix input to JSONObject and remove unneeded Apache dependency

Why
There’s a bug in how we parse the JSON returned to jsonVariation. Before passing to JSONObject we strip off the surrounding braces which causes an exception to be thrown

E/CfClient: Value flag of type java.lang.String cannot be converted to JSONObject
    org.json.JSONException: Value flag of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:111)
        at org.json.JSONObject.<init>(JSONObject.java:163)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at io.harness.cfsdk.CfClient.jsonVariation(CfClient.java:872)
        at com.example.android_sdk_test.MainActivity.lambda$onCreate$2(MainActivity.java:146)
        at com.example.android_sdk_test.MainActivity.$r8$lambda$yX3gDMwxpCIvBmOil3jvG5PQc7c(Unknown Source:0)
        at com.example.android_sdk_test.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

Testing
Manual + new unit test